name: int222-frontend
on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    needs: prepare
    runs-on: ubuntu-20.04

    steps:
    - name: Set env
      run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/main" ] && echo 'prd' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Create .env file
    #   run: |
    #     touch .env
    #     echo DB_URL=${{ secrets.VAR }} >> .env

    - name: Login to Github Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/team-vaxxi/int222-frontend:${{ env.ENV_NAME }}

    - name: Publish compose file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ./docker-compose.${{ env.ENV_NAME }}.yml
        target: ~/int222-related/frontend/${{ env.ENV_NAME }}/

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - name: Set env
      run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/main" ] && echo 'prd' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV

    - name: Run application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker-compose -f ~/int222-related/frontend/${{ env.ENV_NAME }}/docker-compose.${{ env.ENV_NAME }}.yml pull
          docker-compose -f ~/int222-related/frontend/${{ env.ENV_NAME }}/docker-compose.${{ env.ENV_NAME }}.yml up -d